version: '3.8'

services:
  slotmachine-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slotmachine-client
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - slotmachine-network

networks:
  slotmachine-network:
    driver: bridge
